version: '3'
services:
  frontend:
    build: ./client
    ports:
      - "80:80"  # Exposing frontend on port 80
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./server
    ports:
      - "5001:5001"  # Exposing backend on port 5001
    environment:
      - PORT=5001
    networks:
      - app-network

networks:
  app-network:
    driver: bridge